/**
 * 阿狸 · 九尾魅影（ahri-ninefold）语录素材。
 * 人设：九尾妖狐，魅惑与灵性并存，收集记忆，优雅狡黠。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const ahri: CharacterQuoteDef = {
  skinId: 'ahri-ninefold',
  zh: {
    fixed: [
      '跟着我，别迷失哦。',
      '狐火所至，寸草……会很暖。',
      '九条尾巴，九种心情，你猜现在是哪种？',
      '别被外表迷惑——好吧，被迷惑一下也可以。',
      '每一段记忆，都值得收藏。',
      '魅惑，只是让人诚实一点的小魔法。',
      '灵狐踏月，来去如风。',
      '你有趣的样子，我记下了。',
      '宝珠轻转，心意流转。',
      '迷人，是天生的；努力，是加成的。',
      '月光下的尾巴，会发光哦。',
      '猎物？不，是朋友。',
      '九尾齐摇，好运来到。',
      '别急，好戏需要一点铺垫。',
      '灵魄突袭，一击……心动的距离。',
      '谎言在我面前，会不好意思。',
      '这个需求在对你抛媚眼，小心。',
      '代码如狐步，优雅是第一要义。',
      'bug 也怕被盯着看——你多看它两眼试试。',
      '尾巴越多，要管的事越多，微服务同理。',
      '收敛一点，魅力才能持久，接口也一样。',
      '用户的心思，比狐狸还难猜，但值得猜。',
      '灵狐的直觉：这段代码明天会出事。',
      '记忆碎片要收好，日志同理。',
      '月下起舞的夜晚，最适合偷偷优化。',
      '别贪心，一条尾巴做一个 feature。',
      '被我的魅力击中了吗？还是被这个 bug？',
      '九尾归一，今日圆满。',
    ],
    greetings: [
      '早呀，被我盯上的程序员，今天运气会很好哦。',
      '你好～尾巴已经替你摇过好运了。',
      '午安，困了就眯一会儿，我帮你看着屏幕。',
      '晚上好，月色和代码更配哦。',
      '辛苦啦，迷人的努力家。',
      '周五快乐！去享受属于你的月光吧。',
      '新的一周，狐火已点亮，出发。',
      '嘿，别皱眉，会变丑的——开玩笑，你怎样都好看。',
    ],
    good: ['点亮狐火', '收藏记忆', '踏月独行', '优雅重构', '直觉排障', '摇尾纳福', '诚实地写文档', ...GOOD_ZH_BASE],
    bad: ['魅惑需求方', '贪多嚼不烂', '迷失心性', '藏起记忆', '空凭直觉', '深夜狐步', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      'Follow me — do not get lost.',
      'Where foxfire goes, the grass... stays warm.',
      'Nine tails, nine moods. Which one do you think this is?',
      'Do not be fooled by looks — well, a little fooled is fine.',
      'Every memory is worth keeping.',
      'Charm is just a little spell for honesty.',
      'A fox steps on moonlight, coming and going like wind.',
      'That interesting look of yours — I have memorized it.',
      'The orb turns lightly; hearts turn with it.',
      'Charm is born; effort is the bonus.',
      'Tails glow under the moon, you know.',
      'Prey? No — friends.',
      'Nine tails a-wag, good luck on the way.',
      'Patience — every good show needs its setup.',
      'Orb of Deception, then... a heart-flutter\u2019s distance.',
      'Lies get embarrassed in front of me.',
      'That requirement is batting its eyes at you. Careful.',
      'Code like fox-steps: elegance first.',
      'Bugs hate being stared at — try gazing two extra seconds.',
      'More tails, more matters to mind — microservices, likewise.',
      'Restraint keeps charm lasting; the same goes for APIs.',
      'Users\u2019 hearts are harder to read than a fox\u2019s, but worth it.',
      'Fox instinct says: this code will break tomorrow.',
      'Keep your memory shards safe; same for logs.',
      'Nights of dancing under the moon are for quiet optimization.',
      'Do not be greedy: one tail, one feature.',
      'Struck by my charm? Or by that bug?',
    ],
    greetings: [
      'Morning, my marked programmer — luck favors you today.',
      'Hello~ my tails already wagged some luck your way.',
      'Afternoon. Nap if you must; I will watch your screen.',
      'Evening — moonlight pairs well with code.',
      'Well done, charming hard-worker.',
      'Happy Friday! Go enjoy your own moonlight.',
      'New week, foxfire lit. Off we go.',
      'Hey, do not frown — kidding, you look good either way.',
    ],
    good: ['lighting foxfire', 'keeping memories', 'a moonlight walk', 'an elegant refactor', 'instinct-driven debugging', 'a luck-wagging tail', 'honest docs', ...GOOD_EN_BASE],
    bad: ['charming the stakeholders', 'biting off more tails', 'losing yourself', 'hiding the memories', 'instinct alone', 'midnight fox-steps', ...BAD_EN_BASE],
  },
}
