/**
 * 慕沛灵 · 桃夭（mupeiling-blossom）语录素材。
 *
 * 人设：落云宗药园女修，温软恬静，惜花惜人。语录 = 原著风台词 +
 * 程序员问候 + 「药园×代码」跨界梗；黄历宜忌偏养护系。
 */
import type { CharacterQuoteDef } from './types.ts'

export const blossom: CharacterQuoteDef = {
  skinId: 'mupeiling-blossom',
  zh: {
    fixed: [
      // ── 原著风 ──
      '韩立，你我同门一场，何必如此刀兵相向……',
      '这桃花落得再美，也不及那人生若只如初见。',
      '我是落云宗药园的女修，只愿守一方清净药田。',
      '你说的修仙长生，在我眼里不及一炉安神丹。',
      '药园四季，春桃秋菊，都各有各的缘分。',
      '莫要急着赶路，且看这山间晨曦可好。',
      '丹炉火候差一分，药性便谬以千里。',
      '花开有时，谢亦有时，强求不得。',
      '这株灵草性子倔，得顺着它来。',
      '药香伴晨露，是一日里最好的时辰。',
      '师尊常说，炼丹先炼心。',
      '桃花酿要埋三年才开封，急什么呢。',
      '灵田要日日照看，功夫才不欺人。',
      '你眉间有倦色，来喝盏安神茶吧。',
      '草木有灵，你善待它，它便善待你。',
      '落云宗的春日，桃瓣能铺满整条山道。',
      '丹成那一刻的心静，比什么都珍贵。',
      '世人求丹药，我却更爱种药的光景。',
      '夜里药圃有露气，记得添件衣裳。',
      '缘分到了，灵草自己会开花。',
      // ── 药园 × 代码 ──
      '你说的 debug，和炼丹祛杂是一样的道理。',
      '注释如药引，后人读方才不致迷路。',
      '祖传代码如老药田，翻土前先拜一拜。',
      '变量命名要像灵草一样，见名知性。',
      '重构如移栽，选好时节，根才伤得少。',
      '测试是试药，宁可苦口，不可省去。',
      '代码重复如药性相冲，早晚要出事。',
      '你那个 CI，我瞧着像丹房的控火阵。',
      '上线如开炉，火候到了自然丹成。',
      '删库犹如焚田，万万使不得。',
      '回滚不是失败，是给自己留的后悔药。',
      '需求变更如春天气候，备好蓑衣就不怕。',
      '文档荒废的宗门，弟子入门都要多走三年弯路。',
      '一行日志一寸香，出了事才好问诊。',
      '内存泄漏，像药田漏水，日积月累便荒了。',
      '并发如百草同炉，君臣佐使要分明。',
      '别在深夜做重大决定，丹火不稳。',
      '魔法数字如无名毒草，标上名字才敢碰。',
      '递归一层层深入，像极了采药入山，记得留回路。',
      '你的终端一片绿字，倒像我药圃的春色。',
      'Deadline 之前，先深呼吸三息。',
      '小步提交，如细水浇田。',
      '代码 review 如品丹，别人的方子也能学。',
      'Warning 不理，早晚成患。',
      '那句 Hello World，是每个修士的入门心法。',
      '遇事不决，先写测试，如同先辨药性。',
      '降级预案如护山大阵，平时不见，危时救命。',
      '写完这行就休息吧，药要文火，人要慢养。',
    ],
    greetings: [
      '道友早安，今日代码如春芽，要好好呵护呀。',
      '程序员道友，昨夜睡得可好？莫要熬夜伤神。',
      '早上好呀，愿你的编译如春风拂过，一遍就过。',
      '道友辛苦了，写了这么久，歇歇眼睛看看窗外的花吧。',
      '午后困倦么？我这有一盏提神灵茶，请慢用。',
      '晚上好，夜深了，记得存盘再走。',
      '新的一周，愿你的需求如落花，轻轻地来，轻轻地走。',
      '今天啦，愿你顺利收工，过一个桃花般柔软的周末。',
      '道友，喝口热水，bug 也是因缘，会化的。',
      '早安，今日宜心平气和，忌和自己较劲。',
      '午安呀，饭后走走，灵感常在散步时来敲门。',
      '道友晚安，今天的努力，药田都记着呢。',
    ],
    good: [
      '静心重构', '补全测试', '写清注释', '小步提交', '整理文档',
      '早睡早起', '备份代码', '向人道谢', '清理死代码', '泡一壶好茶',
      '赏花片刻', '读一页源码', '问候同门', '修剪旧接口',
    ],
    bad: [
      '深夜上线', '删库跑路', '复制粘贴咒', '跳过测试', '并发乱改',
      '猛灌提神丹', '和人对线', '囤积需求', '硬改祖传代码', '无备份清田', '带病熬夜',
    ],
  },
  en: {
    fixed: [
      // ── novel-flavored ──
      'Han Li, we were of the same sect — must it come to blades?',
      'No blossom falls as beautifully as a first meeting.',
      'I keep the herb garden of Falling Cloud Valley; a quiet plot suits me.',
      'Your immortality is worth less to me than one furnace of calming pills.',
      'The garden has its seasons — spring peach, autumn chrysanthemum, each its own fate.',
      'No need to rush the road; look, the mountain dawn is lovely.',
      'One degree off in the furnace and the whole batch is ruined.',
      'Blooms open in their own time; never force them.',
      'This spirit herb is stubborn — coax it, never rush it.',
      'The master says: refine the heart before the pill.',
      'Dew on the herbs at dawn is the finest hour of the day.',
      'When the time comes, the spirit herb flowers on its own.',
      // ── garden × code ──
      'Debugging is just refining away impurities — same as alchemy.',
      'Comments are the herb guide; follow them and you will not get lost.',
      'Legacy code is an old herb field — bow before you till it.',
      'Name variables like spirit herbs: known at a glance.',
      'Refactoring is transplanting; pick the season, spare the roots.',
      'Tests are tasting the brew — bitter, but never skip it.',
      'Duplicated code conflicts like mismatched herbs; it ends badly.',
      'Your CI looks like the furnace-control array in my pill room.',
      'Deploying is opening the furnace — right heat, right pill.',
      'Deleting the database is burning the field. Never.',
      'Rollback is not failure; it is the regret pill you saved for yourself.',
      'Changing requirements are spring weather — carry a raincoat.',
      'A line of log is an inch of incense — you will need it when trouble comes.',
      'Memory leaks are water seeping from the field: slow, silent ruin.',
      'Concurrency is a hundred herbs in one furnace — order the recipe well.',
      'No big decisions late at night; the furnace fire is unsteady.',
      'Recursion goes deep like herb-gathering in the mountains — always leave a path back.',
      'Finish this line, then rest. Pills need slow fire; people need slow care.',
    ],
    greetings: [
      'Good morning, fellow cultivator — tend your code like spring sprouts.',
      'Hello, programmer! Sleep well? Do not burn the midnight oil.',
      'May your builds pass on the first try, like a spring breeze.',
      'You have worked long — rest your eyes on the flowers outside.',
      'Afternoon slump? A sip of spirit tea, slowly.',
      'Good evening — remember to save and commit before you leave.',
      'Friday at last. May your weekend be soft as peach petals.',
      'Good night. The herb garden remembers today\u2019s effort.',
    ],
    good: [
      'a calm refactor', 'writing tests', 'clear comments', 'small commits', 'tidying docs',
      'an early night', 'backing things up', 'thanking a teammate', 'pruning dead code', 'a pot of good tea',
      'a walk among flowers', 'reading source code', 'greeting a fellow', 'trimming old APIs',
    ],
    bad: [
      'a midnight deploy', 'deleting the repo', 'copy-paste spells', 'skipping tests', 'fiddling concurrency',
      'too much caffeine', 'picking fights', 'hoarding tickets', 'hard-patching legacy code', 'clearing fields without backup', 'coding while sick', 'all-nighters',
    ],
  },
}
