/**
 * 韩立 · 青竹（hanli-daoist）语录素材。
 *
 * 人设：青袍道人，苟道谨慎，恩怨分明。语录 = 原著风台词 + 程序员
 * 问候 + 「苟道×防御性编程」跨界梗；黄历宜忌偏稳扎稳打系。
 */
import type { CharacterQuoteDef } from './types.ts'

export const daoist: CharacterQuoteDef = {
  skinId: 'hanli-daoist',
  zh: {
    fixed: [
      // ── 原著风 ──
      '贫道行走江湖，向来人不犯我，我不犯人。',
      '青竹蜂云剑出鞘之日，便是了却因果之时。',
      '修仙之路，贵在坚持，切莫贪功冒进。',
      '留得青山在，哪怕没柴烧。',
      '这雷光再烈，也照不亮人心里的贪婪。',
      '天道酬勤，我韩立能走到今日，靠的是一步一个脚印。',
      '小心驶得万年船，谨慎二字便是我的道。',
      '财不露白，艺不轻传，锋芒毕露者死得早。',
      '结丹也好，元婴也罢，先活下来再谈。',
      '筑基百艺，逃生第一。',
      '此宝虽好，也要有命拿才行。',
      '恩怨分明，一码归一码。',
      '莫要小瞧任何人，扫地僧亦有惊天的手段。',
      '闭关百日，不如出门历一次劫。',
      '机缘是天给的，命是自己保的。',
      '我这一身伤疤，比任何功法都实在。',
      '遇强则遁，不是怯懦，是智慧。',
      '瓶中灵液一滴，胜过苦修十日。',
      '别人笑我太苟，我笑他人看不穿。',
      '大道三千，我选最稳的那一条。',
      // ── 苟道 × 代码 ──
      '防御性编程，就是代码界的铁布衫。',
      '上线前不灰度，如同渡劫不备法宝。',
      '异常要捕获，因果要了结，不可留尾巴。',
      '备份是保命符，贫道从不离身。',
      '重构先写测试，如动手先探对方底细。',
      '那些 warning，都是劫前的异象，不可不察。',
      '性能优化如炼体，先测再炼，莫凭感觉。',
      '删日志如毁证据，出事哭都来不及。',
      '祖传代码深似海，改动前先焚香三炷。',
      'try-catch 不是万能护身符，吞掉异常等于埋雷。',
      '灰度发布是为稳妥，全量上线是为赌命。',
      '代码审计如神识扫过，一处不落。',
      '依赖升级如换法宝，先看相性，再看出处。',
      '单点故障，是阵法的死穴，也是系统的。',
      '注释写「这里别动」的祖师，必有一段血泪往事。',
      '缓存虽好，失效策略才是真功夫。',
      '文档即藏经阁，荒废了，后人只能重修。',
      '常在河边走，哪有不湿鞋；常写代码，哪有无 bug。',
      'review 别只看自家，多看别家，武学方能精进。',
      '监控告警，就是护山大阵的警钟。',
      '技术债如心魔，越拖越强，早晚要正面一战。',
      '一行代码一行命，手抖之前多思量。',
      '编译过了只是筑基，测试过了才算结丹。',
      '递归无出口，如入幻阵，进得来出不去。',
      '命名随意，后患无穷；见名知意，功德无量。',
      '上线如渡劫，挑个良辰吉日，别赶在周末前。',
      '枪打出头鸟，未测完的功能别抢着发。',
      '遇事不决先回滚，保住青山，再图后续。',
    ],
    greetings: [
      '道友早安，代码写完记得自查一遍，稳妥为上。',
      '程序员道友，久坐伤身，起来活动活动筋骨吧。',
      '早，今日第一件事：想清楚再动手，省得返工。',
      '道友辛苦，风险大的改动，先备份再动手。',
      '午后好，困倦时莫改核心代码，容易出事。',
      '晚上好，深夜 production 慎动，贫道言尽于此。',
      '新的一周，愿你的需求都排得明明白白。',
      '今天收好尾巴，别把隐患留到明天。',
      '道友，遇到诡异的 bug，先怀疑环境，再怀疑自己。',
      '早安，今日宜稳扎稳打，忌心浮气躁。',
      '午安，饭要一口口吃，代码要一行行写。',
      '道友晚安，早点休息，明日的战场还大。',
    ],
    good: [
      '备份存档', '补齐测试', '审阅代码', '小步提交', '灰度发布',
      '加固监控', '读一页源码', '还技术债', '早睡养神', '请教前辈',
      '加固边界', '静心重构', '演练预案', '复盘总结',
    ],
    bad: [
      '赶在周末前上线', '裸奔无备份', '吞掉异常', '硬闯祖传代码', '跳过测试',
      '凌晨动刀', '盲目升级', '炫耀锋芒', '孤军奋战', '欠下心魔债', '不设防上线',
    ],
  },
  en: {
    fixed: [
      // ── novel-flavored ──
      'I harm no one who does not harm me — that has kept me alive.',
      'The day my sword leaves its sheath is the day debts are settled.',
      'Cultivation rewards patience; greed invites calamity.',
      'Stay alive first; talk of breakthroughs later.',
      'No matter how fine the treasure, you must live to keep it.',
      'Caution is my Dao. Two words, ten thousand years.',
      'Never underestimate anyone — even the sweeper may hide heaven-shaking skill.',
      'Fortune is given by heaven; your life is kept by yourself.',
      'My scars are more honest than any manual.',
      'Fleeing a stronger foe is not cowardice; it is strategy.',
      'Great Dao has three thousand paths — I take the sturdiest.',
      'Others laugh at my caution; I laugh at their blindness.',
      // ── survival × code ──
      'Defensive programming is the Iron Shirt of code.',
      'Deploying without a canary is facing tribulation barehanded.',
      'Catch exceptions; settle causes and effects. Leave no tails.',
      'Backups are life-saving talismans. I never leave home without mine.',
      'Write tests before refactoring — scout before you strike.',
      'Those warnings are omens before a tribulation. Heed them.',
      'Optimize like body training: measure first, then refine.',
      'Deleting logs is destroying evidence. You will weep.',
      'Legacy code runs deep. Burn three incense sticks before touching it.',
      'A catch-all that swallows errors is burying a mine, not defusing one.',
      'Gradual rollout is prudence; big-bang deploy is gambling with your life.',
      'Audit code like spiritual sense sweeping a room — miss nothing.',
      'Upgrading dependencies is swapping a treasure: check origin, check fit.',
      'A single point of failure is the death acupoint of any array — or system.',
      'The ancestor who commented "do not touch" had blood-soaked reasons.',
      'Caching is fine; the invalidation strategy is the real kung fu.',
      'Docs are the sect archives. Neglect them and disciples relearn everything.',
      'To write code is to birth bugs. Accept it, then test for it.',
      'Review others\u2019 code too — that is how martial arts improve.',
      'Monitoring and alerts are the warning bells of the mountain-guarding array.',
      'Technical debt is an inner demon: the longer you feed it, the stronger it gets.',
      'Compiling is Foundation Establishment; passing tests is Core Formation.',
      'Recursion without an exit is a phantom array — easy in, no way out.',
      'Deploy like facing tribulation: pick an auspicious day. Never a Friday.',
      'When in doubt, roll back. Keep the green mountain; fight another day.',
    ],
    greetings: [
      'Good morning, fellow — review your own code before others must.',
      'Hello, programmer. Sit less, stretch more.',
      'Morning. Think it through before you type; rework wastes qi.',
      'Risky change? Back it up first. Trust me on this.',
      'Afternoon — avoid editing core code while drowsy.',
      'Good evening. Touching production at midnight... I said what I said.',
      'A new week — may your tickets be neatly ordered.',
      'Friday. Tie up loose ends; leave no traps for the weekend.',
    ],
    good: [
      'backing everything up', 'writing tests', 'code review', 'small commits', 'a canary release',
      'hardening the monitors', 'reading source', 'paying down debt', 'an early night', 'asking an elder',
      'guarding the borders', 'a calm refactor', 'running a drill', 'a quiet retrospective',
    ],
    bad: [
      'a Friday deploy', 'flying without backup', 'swallowing exceptions', 'charging into legacy code', 'skipping tests',
      'midnight surgery', 'blind upgrades', 'flashing your edge', 'going alone', 'feeding the inner demon', 'deploying unguarded', 'ignoring omens',
    ],
  },
}
