/**
 * 伊泽瑞尔 · 符文远征（ezreal-relicrun）语录素材。
 * 人设：皮尔特沃夫的天才探险家，自信满满，护手开路，寻宝直觉一流。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const ezreal: CharacterQuoteDef = {
  skinId: 'ezreal-relicrun',
  zh: {
    fixed: [
      '要跟着宝藏的直觉走！',
      '时光倒流？不，是精准闪现。',
      '我的护手，可比你的法杖帅多了。',
      '探险的乐趣，就在于下一秒的未知。',
      '嘿，看招！精华跳跃！',
      '宝藏就在前面，跟紧我！',
      '别担心，我有计划……大概。',
      '地图我来记，路你们来开。',
      '每个遗迹背后，都藏着一段故事。',
      '冲动是探险家的美德，谨慎是活着的前提。',
      '你又迷路了？我可是活地图。',
      '符文指引方向，直觉发现宝藏。',
      '你说的「探索性测试」，听起来像我的日常。',
      '新技术就像新遗迹，先探清楚再进去。',
      'documentation 是藏宝图，别嫌它旧。',
      '装好依赖再出发，半路没粮是大忌。',
      '宝藏与陷阱只隔一层地板——所以要看 changelog。',
      '精准弹幕，覆盖需求；奥术跃迁，切个分支。',
      '每次重构都是一次探险：地图画好，装备带齐。',
      '我的直觉从不出错……好吧，很少出错。',
      '考古学家最懂版本回滚的价值。',
      '好奇心是第一生产力。',
      '这个 bug 藏得挺深，可惜我是专业的。',
      '危险？那正是有趣的部分。',
      '先放大招再说话：精准弹幕，需求清空。',
      '探险归来，记得写下见闻——文档，就是你的游记。',
      '相信队友，就像相信我的护手。',
      '出发！这次一定找到那个传说中的祖传注释。',
    ],
    greetings: [
      '早啊探险家！今天的技术栈，就是今天的遗迹！',
      '你好呀，我掐指一算，你今天会挖到大宝（bug）。',
      '午安，补给（午饭）吃饱了再上路。',
      '晚上好！夜探遗迹要结伴，改核心代码要备份。',
      '干得漂亮！这波探索满分！',
      '周五快乐！周末去哪里探险呀？',
      '新的一周，新的藏宝图（需求文档）！',
      '跟紧我，宝藏就在下一个 sprint！',
    ],
    good: ['出发探新', '画好地图', '带上补给', '写下游记', '跟随直觉', '精准确认', '满装出发', ...GOOD_ZH_BASE],
    bad: ['空手探穴', '不看藏宝图', '半路断粮', '单枪匹马', '轻信陷阱', '原地打转', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      'You gotta follow your treasure sense!',
      'Time warp? No — a precision Flash.',
      'My gauntlet is way cooler than your staff.',
      'The fun of exploring is the unknown next second.',
      'Hey, watch this — Essence Flux!',
      'Treasure ahead. Keep up!',
      'Do not worry, I have a plan... roughly.',
      'I will map the route; you clear the path.',
      'Behind every ruin hides a story.',
      'Impulse is an explorer\u2019s virtue; caution is how you stay alive.',
      'Lost again? I am a living map.',
      'Runes point the way; instinct finds the gold.',
      'Your "exploratory testing" sounds like my daily job.',
      'New tech is a new ruin: scout it before entering.',
      'Documentation is a treasure map. Never mind that it is old.',
      'Pack your dependencies before departing; running out mid-way is fatal.',
      'Treasure and trap are one floor apart — read the changelog.',
      'Trueshot Barrage to clear the requirements; Arcane Shift to switch branches.',
      'Every refactor is an expedition: draw the map, pack the gear.',
      'My instinct never fails... alright, rarely.',
      'Archaeologists understand version rollback best.',
      'Curiosity is the primary productive force.',
      'That bug hides deep — too bad I am a professional.',
      'Danger? That is the fun part.',
      'Exploration done? Write down what you saw — docs are your travelogue.',
      'Trust your team like I trust my gauntlet.',
      'Let\u2019s move! This time we find the legendary legacy comment.',
    ],
    greetings: [
      'Morning, explorer! Today\u2019s tech stack is today\u2019s ruin!',
      'Hello! My senses say you will dig up a big bug today.',
      'Afternoon — stock up (lunch) before the road.',
      'Evening! Ruins at night need a partner; core code needs a backup.',
      'Nice shot! Full marks for exploration!',
      'Happy Friday! Where to this weekend?',
      'New week, new treasure map (the spec)!',
      'Stay close — the loot is in the next sprint!',
    ],
    good: ['exploring the new', 'drawing the map', 'packing supplies', 'writing the travelogue', 'trusting your gut', 'a precise confirm', 'a full loadout', ...GOOD_EN_BASE],
    bad: ['caving empty-handed', 'ignoring the map', 'running out of supplies', 'going solo', 'trusting the trap', 'circling in place', ...BAD_EN_BASE],
  },
}
