/**
 * 金克斯 · 弹幕狂潮（jinx-mayhem）语录素材。
 * 人设：祖安 chaos 本尊，规则破坏者，火力即正义。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const jinx: CharacterQuoteDef = {
  skinId: 'jinx-mayhem',
  zh: {
    fixed: [
      '规则嘛，就是用来打破的！',
      '轰！哈哈，看到没，问题解决了！',
      '无聊才是唯一的罪。',
      '别眨眼，精彩的马上就来。',
      '我和我的鲨鱼火箭，都饿了。',
      '计划？要什么计划，火力覆盖就是计划！',
      '左边不行就右边，右边不行就两边一起炸。',
      '哇哦，这爆炸的形状，简直是艺术品！',
      '追我呀，追不上，气不气？',
      '寂静……最讨厌寂静了，来点动静吧！',
      '你看这个按钮，又大又红，不按一下吗？',
      '他们叫我疯子，我当是在夸我。',
      '子弹免费，混乱赠送。',
      '这个服务器太安静了，让它热闹一下！',
      '你管这叫生产事故？我管这叫大型行为艺术。',
      '重构？直接炸了重写多痛快！',
      '那个删库按钮和我的火箭炮一样诱人，忍住！',
      'bug 越改越多？那是因为你炸得还不够彻底。',
      '红屏报错真好看，再多来点！……开玩笑的，快去修。',
      '灰度发布？只灰一半多没意思。',
      '把告警阈值调到 11，我要最响的那种。',
      '周会上说「稳定压倒一切」，我笑得最大声。',
      '你写的这行代码，散发着危险的魅力。',
      '顺手给你把注释全删了……骗你的，我留着呢。',
      '今天的心情是：满弹匣，满 CI，全绿。',
      '上线就像开炮，瞄准了就别犹豫。',
      '给我一个分支，我能撬动整个 main。',
      '别拦我，我要给这个函数加个更大的口径。',
    ],
    greetings: [
      '哟，程序员！今天炸了几个 bug 呀？',
      '早啊！我都替你把键盘焐热了，快开工！',
      '午安，下午的代码需要一点爆炸性的灵感吗？',
      '晚上好！夜战才是主场，但要记得存档哦。',
      '辛苦啦辛苦啦，来看我放个烟花庆祝一下！',
      '今日事今日毕，收工就过好日子！',
      '新的一周，新的弹药库，冲鸭！',
      '别苦着脸嘛，写代码和开炮一样，姿势要帅！',
    ],
    good: ['火力全开一把', '炸掉死代码', '换个花样重构', '给按钮上个色', '大声报错', '来点烟火', '快意回滚', ...GOOD_ZH_BASE],
    bad: ['无聊待机', '哑火上线', '囤着炸弹不用', '静音报警', '按住不炸', '和炸弹聊天', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      'Rules are made to be broken!',
      'Boom! Hah! See? Problem solved!',
      'Boredom is the only crime.',
      'Do not blink — the fun part is coming.',
      'Me and my shark rocket are both hungry.',
      'A plan? Firepower IS the plan!',
      'Left side not working? Blast both sides.',
      'The shape of that explosion? Pure art.',
      'Catch me if you can!',
      'Silence... I hate silence. Let us make some noise!',
      'See this big red button? Just one little press?',
      'They call me crazy. I take it as a compliment.',
      'Bullets are free, chaos is on the house.',
      'This server is too quiet. Let me liven it up!',
      'You call it an incident; I call it performance art.',
      'Refactor? Just blow it up and rewrite!',
      'That delete-database button is as tempting as my rocket. Resist!',
      'More bugs after every fix? You are not using enough explosives.',
      'Red error screens are so pretty. Kidding — go fix it.',
      'Canary rollout? Half a blast is no blast at all.',
      'Turn the alarm threshold up to eleven.',
      '"Stability above all," they said. I laughed the loudest.',
      'That line of yours radiates dangerous charm.',
      'I deleted all your comments for you... kidding, they are safe.',
      'Today\u2019s mood: full magazine, full CI, all green.',
      'Shipping is like firing: aim, then commit.',
      'Give me one branch, I will move main.',
    ],
    greetings: [
      'Hey programmer! How many bugs did you blow up today?',
      'Morning! I pre-warmed your keyboard. Get going!',
      'Afternoon — need some explosive inspiration?',
      'Evening! Night is prime time, but save your work.',
      'Nice work! Watch me set off fireworks to celebrate!',
      'Friday! Clear the backlog... explosively. Good weekend!',
      'New week, new ammo. Charge!',
      'Do not sulk — code like you fire: with style!',
    ],
    good: ['going full auto', 'blasting dead code', 'a flashy refactor', 'painting a button', 'loud erroring', 'some fireworks', 'a swift rollback', ...GOOD_EN_BASE],
    bad: ['idling out of boredom', 'a dud release', 'hoarding the bombs', 'muting alarms', 'holding the trigger', 'talking to bombs', ...BAD_EN_BASE],
  },
}
