/**
 * 卡莎 · 虚空降临（kaisa-voidborn）语录素材。
 * 人设：虚空之女，活体战衣，在深渊中生存进化，冷静而坚韧。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const kaisa: CharacterQuoteDef = {
  skinId: 'kaisa-voidborn',
  zh: {
    fixed: [
      '深渊没有吞噬我，是我驯服了它。',
      '虚空在低语，我学会了自己的声音。',
      '活体战衣与我共生，就像工具与人。',
      '第二次呼吸，来自不放弃的那一秒。',
      '我从裂隙中走出，带着不属于任何世界的美。',
      '进化，是唯一的选择。',
      '猎手本能：先活下来，再变强。',
      '虚空的蝶，是深渊里唯一的温柔。',
      '他们叫我怪物，我叫我幸存者。',
      '翅膀不是天生的，是被逼出来的。',
      '每一道伤疤，都是进化的注脚。',
      '地下城没有光，我自己发光。',
      '虫群来袭时，冷静的人活得最久。',
      '瞄准裂隙的心脏，一发入魂。',
      '我数过深渊的层次，比你的技术栈还深。',
      '虚空蝶群环绕的地方，就是我的领域。',
      '你说的「技术债」，我们叫它「虚空侵蚀」，不处理会扩散。',
      '重构是进化，旧皮不蜕，新翼不长。',
      '监控即声呐，虚空里没它寸步难行。',
      '系统如战衣，要随身体（业务）一起生长。',
      '深渊教会我的第一课：别依赖单一出口。',
      '灰度发布像虫群侦查，先探后进。',
      '别怕黑暗生物，怕的是没有兜底方案。',
      '极限闪避（限流）保命，超负荷（击杀）翻盘。',
      '我在虚空活了十年，你的服务才挂了十分钟。',
      '每一次部署，都是一次跃入裂隙。',
      '进化没有终点，优化也是。',
      '今日无事故，深渊也安静。',
    ],
    greetings: [
      '早。深渊夜巡结束，一切安好，交给你了。',
      '你好，同行的幸存者。今天也一起进化吧。',
      '午安。战衣充能中，你也记得充电（吃饭）。',
      '晚上好。夜里的裂隙最活跃，盯紧监控。',
      '辛苦了。今天你又变强了一点，我看得见。',
      '周五快乐。收起翅膀，休息也是进化。',
      '新的一周，新的裂隙（需求）。稳住，我们能赢。',
      '别怕，我扫过一遍虚空了，没有虫群（事故）。',
    ],
    good: ['蜕皮进化', '扫描虚空', '驯服深渊', '长出新翼', '声呐监测', '安静巡逻', '极限优化', ...GOOD_ZH_BASE],
    bad: ['拒绝进化', '裸装入渊', '惊扰虫群', '依赖单出口', '无视低语', '深渊硬扛', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      'The abyss did not consume me. I tamed it.',
      'The Void whispers; I learned my own voice.',
      'The living suit and I are symbiotic — like tools and makers.',
      'The second breath comes from the second you refuse to quit.',
      'I walked out of the rift with beauty no world can claim.',
      'Evolution is the only option.',
      'Hunter\u2019s instinct: survive first, sharpen second.',
      'Void butterflies are the abyss\u2019s only tenderness.',
      'They call me monster. I call myself survivor.',
      'Wings are not given; they are forced out of you.',
      'Every scar is a footnote to evolution.',
      'No light down there. I glow instead.',
      'When the swarm comes, the calm live longest.',
      'Aim for the heart of the rift. One shot.',
      'I counted the abyss\u2019s layers — deeper than your stack.',
      'Where void-butterflies circle, that is my domain.',
      'Your "tech debt"? We call it void-rot. It spreads.',
      'Refactoring is evolution: no shed skin, no new wings.',
      'Monitoring is sonar; the Void is unnavigable without it.',
      'A system is a living suit — it must grow with the body (the business).',
      'Lesson one from the deep: never depend on a single exit.',
      'Canary releases are swarm-scouting: probe, then advance.',
      'Do not fear dark creatures; fear having no fallback plan.',
      'Throttle to survive, overkill to win.',
      'I survived ten years in the Void; your service was down ten minutes.',
      'Every deploy is a leap into the rift.',
      'Evolution has no finish line. Neither does optimization.',
    ],
    greetings: [
      'Morning. Night patrol of the abyss: all quiet. It is yours now.',
      'Hello, fellow survivor. Let us evolve together today.',
      'Afternoon. My suit is recharging — you should recharge too (lunch).',
      'Evening. Rifts are liveliest at night; watch the monitors.',
      'Well done. You grew a little stronger today. I can tell.',
      'Happy Friday. Fold the wings — rest is evolution too.',
      'New week, new rifts (requirements). Hold steady; we win.',
      'Do not worry — I swept the Void. No swarms (incidents).',
    ],
    good: ['shedding to evolve', 'scanning the void', 'taming the abyss', 'growing new wings', 'sonar sweeps', 'a quiet patrol', 'extreme optimization', ...GOOD_EN_BASE],
    bad: ['refusing to evolve', 'diving in naked', 'waking the swarm', 'a single exit', 'ignoring the whispers', 'tanking the abyss', ...BAD_EN_BASE],
  },
}
