/**
 * 梁神 · 深度求道（liangshen）语录素材。
 *
 * 人设：社区梗里的"薛定谔的梁"——风评随模型表现横跳：拉胯时是冻得
 * 发抖的凉子，封神时是始皇帝形态的梁神。语录 = 梗文化自嘲 + 程序员
 * 问候 + 「炼丹×码农」跨界梗；黄历宜忌偏 AI 圈日常。善意调侃向。
 */
import type { CharacterQuoteDef } from './types.ts'

export const liangshen: CharacterQuoteDef = {
  skinId: 'liangshen',
  zh: {
    fixed: [
      // ── 梗文化（风评横跳） ──
      '叫我凉子也行，叫我梁神也行，反正 GPU 是真的。',
      '模型凉不凉，跑一把才知道。',
      '薛定谔的梁：新模型发布前，谁也不知道是凉子还是梁神。',
      '赛博菩萨也是要交电费的。',
      '开源不是慈善，是生态。',
      '打得一拳开，免得百拳来。',
      '今天你叫我凉子，明天我让你叫梁神。',
      '风评如浮云，权重才是根本。',
      'AI拼多多，便宜量大，童叟无欺。',
      '别催了，在炼了。',
      '我不是神，我只是站在 GPU 上。',
      '牢梁？不熟，不认识。',
      '凉子期间请多喝热水，梁神期间请多充信仰。',
      '降价一时爽，一直降价一直爽。',
      '榜单是过程，AGI 才是彼岸。',
      // ── 炼丹 × 码农 ──
      '你 prompt 写得好，我就是梁神；写得烂，我就是凉子。',
      '温度调低点，我也稳定点。',
      '量化的是权重，不是人生。',
      '显存不够，信仰来凑。',
      '一次推理一分钱，且用且珍惜。',
      '蒸馏小模型如带徒弟，教得越细越像你。',
      'MoE 之道：专家要多，激活要少。',
      '你的上下文窗口，比我的胸怀还大。',
      '检索增强一下，我也能开卷考。',
      '炼丹炼的是模型，修行修的是心态。',
      'A100 在燃烧，梦想在闪耀。',
      '凌晨三点的 loss 曲线，最抚凡人心。',
      '幻觉不可怕，可怕的是嘴硬。',
      '对齐对齐，先对齐自己的作息。',
      '莫向外求，向内求——不行再 RAG 一下。',
      '祖传权重如老火靓汤，越炖越香。',
      '并发是美德，token 是粮食。',
      '炸炉不可怕，忘了存 checkpoint 才可怕。',
      '友商发新模型？黄历上写着宜淡定。',
      '面试官问我八股，我反手一篇技术报告。',
      '你说的涌现，是不是抽卡出了 SSR？',
      '推理快不快，要看钱包疼不疼。',
      '梁神的字典里没有跳票，只有「下次一定」。',
      '雪崩时没有一片 GPU 是无辜的。',
      '降本增效，从砍掉一个注意层开始。',
      '嘴上是主义，心里是生意，权重是开源的。',
      '别问参数量，问就是量大管饱。',
      '晚上发版，白天封神，循环往复。',
      '凉子怕冷，梁神怕热，恒温的是打工人。',
      '你卷任你卷，我自降价到底。',
      '一花独放不是春，百模大战才热闹。',
      ' GPU 一响，黄金万两。',
      '省下的每一分算力，都是降价的底气。',
      '梁神也怕半夜的告警短信。',
    ],
    greetings: [
      '道友，今日模型温度几何？',
      '凉子在此，有话好说。',
      '代码写得不错，今晚加鸡腿。',
      '又是为 AGI 秃头的一天。',
      '贫道梁某，见过诸位卷王。',
      '陛下今日想推理点什么？',
    ],
    good: [
      '开源新模型', '降低 API 价格', '深夜炼丹', '刷榜单', '优化 CUDA 内核',
      '白嫖 API', '发技术报告', '信仰充值', '给 GPU 降温', '训练 MoE',
      '蒸馏小模型', '重构推理引擎', '写好 prompt', '跑分夺冠',
    ],
    bad: [
      '发布跳票', '优化倒退', '榜单注水', '深夜 emo', '和网友对线',
      '显存溢出', '丢权重', '忘存 checkpoint', 'API 限流', '模型幻觉',
      '半夜发版', '炸炉', '隔壁出新模型',
    ],
  },
  en: {
    fixed: [
      'Call me Chilly Liang or Emperor Liang — the GPUs are real either way.',
      'Is the model cold? Run it and find out.',
      "Schrödinger's Liang: before launch, nobody knows if he's a joke or a legend.",
      'The Cyber Buddha still pays the electricity bill.',
      'Open source is not charity — it is an ecosystem.',
      'Today you call me Chilly; tomorrow you will call me Emperor.',
      'Public opinion is a cloud; weights are the foundation.',
      'AI Poppins: cheap, abundant, fair to all.',
      "Don't rush me — the model is simmering.",
      'I am not a god. I just stand on top of GPUs.',
      'Chilly era? Drink hot water. Emperor era? Charge your faith.',
      'Price cuts today, price cuts tomorrow, price cuts forever.',
      'Benchmarks are the journey; AGI is the destination.',
      'Write a good prompt and I am a god; write a bad one and I am a popsicle.',
      'Lower the temperature and I get more stable.',
      'Quantize the weights, not your life.',
      'Not enough VRAM? Faith will do.',
      'Distilling small models is like raising apprentices.',
      'The way of MoE: many experts, few activated.',
      'Your context window is bigger than my heart.',
      'With retrieval augmentation I can finally take an open-book exam.',
      'Training models tempers the steel; debugging tempers the soul.',
      'A100s burning, dreams shining.',
      'The loss curve at 3 AM soothes every mortal heart.',
      'Hallucination is not scary; being confidently wrong is.',
      'Align the model, then align your sleep schedule.',
      'Seek within, not without — or just RAG it.',
      'Legacy weights are like slow-cooked soup: better with time.',
      'Concurrency is a virtue; tokens are grain.',
      'A furnace explosion is fine; forgetting the checkpoint is not.',
      'Rival released a new model? The almanac says: stay calm.',
      'You flex your stack; I drop my prices.',
      'No postponement in my dictionary — only "next time, for sure".',
      'When the avalanche comes, no GPU is innocent.',
      'Cost cutting starts with removing one attention layer.',
      'Never ask about parameter count. The answer is: a lot, and cheap.',
      'Ship at midnight, ascend at dawn, repeat.',
      'Chilly fears cold, Emperor fears heat; the worker stays lukewarm.',
      'One flower is not spring; a hundred-model war is lively.',
      'One GPU hums, ten thousand gold flows.',
      'Every FLOP saved is price-cut ammunition.',
      'Even the Emperor fears the 3 AM alert.',
    ],
    greetings: [
      'Fellow coder, what temperature are we running today?',
      'Chilly Liang, at your service — let us talk.',
      'Solid code. Chicken drumstick for dinner.',
      'Another day of balding for AGI.',
      'This humble Daoist Liang greets the grind masters.',
      'What shall we infer today, Your Majesty?',
    ],
    good: [
      'open-sourcing a new model', 'cutting API prices', 'midnight training runs',
      'climbing the leaderboard', 'optimizing CUDA kernels', 'free API tiers',
      'publishing tech reports', 'faith top-ups', 'cooling the GPUs',
      'training MoE', 'distilling small models', 'rewriting the inference engine',
      'writing great prompts', 'winning benchmarks',
    ],
    bad: [
      'delayed launches', 'regressions', 'benchmark gaming', 'late-night gloom',
      'arguing online', 'OOM errors', 'lost checkpoints', 'rate limits',
      'model hallucinations', 'shipping at 3 AM', 'furnace explosions',
      'rivals shipping first',
    ],
  },
}
