/**
 * 银月 · 月华（yinyue-lunar）语录素材。
 *
 * 人设：银月狼族器灵，清冷沉静，千年阅历。语录 = 原著风台词 +
 * 程序员问候 + 「星月×夜班运维」跨界梗；黄历宜忌偏规律作息系。
 */
import type { CharacterQuoteDef } from './types.ts'

export const lunar: CharacterQuoteDef = {
  skinId: 'yinyue-lunar',
  zh: {
    fixed: [
      // ── 原著风 ──
      '月有阴晴圆缺，人有悲欢离合，此事古难全。',
      '我虽是器灵转生，却也想看看这人间烟火。',
      '星光不问赶路人，岁月不负有心人。',
      '月华如水，愿君莫负这良宵。',
      '一轮明月照九州，几家欢乐几家愁。',
      '既是月下之约，便莫要爽约。',
      '银辉所照之处，藏不住心事。',
      '我随主人千年，见过太多聚散。',
      '夜越深，星越亮。',
      '人间的灯火，比星河更暖。',
      '月亮不说话，只是听着。',
      '潮起潮落，皆是月亮的手笔。',
      '莫愁前路，月光会陪你一段。',
      '千年不过一瞬，何况一个 bug 呢。',
      '清辉冷眼，照尽世间痴人。',
      '器灵亦有情，只是不说。',
      '今晚的月色，适合放下执念。',
      '星辰运转自有轨道，强求的会脱轨。',
      '我在剑中等主人，主人在路上等黎明。',
      '夜行者，最懂月光的温柔。',
      // ── 星月 × 代码 ──
      '版本号如月相：alpha 是新月，GA 是满月。',
      '代码如月，有亮面就有暗面。',
      '备份要像月亮，留一份影子在别处。',
      '夜班运维，是最懂凌晨四点的修行者。',
      '日志如星图，排障时按图索骥。',
      '异步任务如潮汐，到点自然来，莫要死等。',
      '轮询不如订阅，守株待兔不如月照大江。',
      '内存如夜空，常量如恒星，变量如流星。',
      '死锁的夜，两颗星互相等待，谁也不肯先眨眼。',
      '发布窗口挑在月圆之夜，人心安定。',
      '代码的美，如月光，安静才有力量。',
      '超时重试三次，如月落月升，总会有转机。',
      '暗色模式是我的主场，护眼又护心。',
      '注释要像月光，柔和地照亮别人的路。',
      'deadline 如月食，躲不过，那就静静看它过去。',
      '重构之夜，旧代码如残月退场，新代码如新月登场。',
      '缓存命中率如云量，多云转晴全看策略。',
      '接口文档如月历，写清楚了，大家都不慌。',
      '程序员看星星：那是三千年前的光，正如祖传代码的注释。',
      '空指针是最深的夜，一步踏空，万劫不复。',
      '单元测试如星宿，各自守住一方天域。',
      '联调之夜，前端后端如牛郎织女，接口是鹊桥。',
      '告警如狼嚎，一声起，众修皆醒。',
      '性能曲线如月轨，看长期趋势，别纠结一夜涨跌。',
      '热修复如月影挪移，悄悄地进村。',
      '写代码如观月，远看朦胧，近看坑坑洼洼。',
      '愿你的系统如明月，阴晴圆缺，总在轨道。',
      '深夜 debug，我与月亮都在陪你。',
    ],
    greetings: [
      '程序员道友，夜深了，月亮提醒你该休息了。',
      '早安，昨夜的 bug 睡一觉再看，往往会自己现形。',
      '道友日安，愿今日如满月，诸事圆满。',
      '晚上好，又是一个和代码相伴的夜晚么？',
      '月色真美，道友，抬头看看窗外吧。',
      '新的一周，愿你如新月渐盈，稳步生长。',
      '道友辛苦，深夜加班时，月光与你同在。',
      '周五好，愿你今晚不用看 oncall 电话。',
      '午安，忙里偷闲，看看云也好。',
      '早安，今天是适合从头梳理的好日子。',
      '道友，深夜的灵感固然美，健康更贵。',
      '晚安，愿你梦里没有未捕获的异常。',
    ],
    good: [
      '观星静心', '梳理日志', '补齐文档', '早睡补觉', '统一代码风格',
      '清理死代码', '备份数据', '写单元测试', '与友夜谈', '月下散步',
      '复盘一夜', '画架构图', '温和沟通', '循序渐进',
    ],
    bad: [
      '深夜爆肝', '死等轮询', '忽视告警', '裸奔上线', '空指针夜航',
      '无图赶路', '硬怼同事', '囤积异步任务', '满负荷运转', '删日志', '闭眼合码',
    ],
  },
  en: {
    fixed: [
      // ── novel-flavored ──
      'The moon waxes and wanes; so do people meet and part.',
      'A spirit reborn in a blade, I still wish to see the mortal world.',
      'Starlight asks nothing of the traveler; time rewards the steadfast.',
      'Moonlight like water — do not waste such a fine night.',
      'One moon over nine provinces: some households joy, some sorrow.',
      'A promise made under the moon must be kept.',
      'Where silver light falls, no secret hides.',
      'I have served my master a thousand years and seen too many partings.',
      'The deeper the night, the brighter the stars.',
      'Mortal lamplight is warmer than the galaxy.',
      'The moon says nothing; it only listens.',
      'Tides rise and fall by the moon\u2019s quiet hand.',
      'A thousand years is but a moment — what then is one bug?',
      'Tonight\u2019s moonlight is made for letting go of old obsessions.',
      // ── moon × code ──
      'Versions are moon phases: alpha the new moon, GA the full moon.',
      'Code is like the moon: a bright side and a dark side.',
      'Back up like the moon — keep a shadow of yourself elsewhere.',
      'Night-shift ops is the true ascetic of 4 a.m.',
      'Logs are star charts; trace them to find your way home.',
      'Async tasks are tides — they arrive on schedule; do not busy-wait.',
      'Subscribe, do not poll. Let the river come to the moon.',
      'Memory is the night sky: constants stars, variables shooting stars.',
      'A deadlock is two stars waiting for each other to blink first.',
      'Deploy on a full-moon night; hearts are calm.',
      'Beautiful code is like moonlight — quiet power.',
      'Retry with backoff three times: moons set, and moons rise again.',
      'Dark mode is my home turf — easy on eyes, easy on heart.',
      'Let comments be moonlight: lighting another\u2019s path, gently.',
      'A deadline is a lunar eclipse — unavoidable; watch it pass calmly.',
      'Refactor night: old code a waning moon, new code a waxing one.',
      'Cache hit rate is cloud cover; strategy decides clear skies.',
      'API docs are the lunar calendar; written well, no one panics.',
      'Programmers watching starlight see three-thousand-year-old light — like legacy comments.',
      'The null pointer is the darkest night: one misstep, no return.',
      'Unit tests are constellations, each holding its quarter of the sky.',
    ],
    greetings: [
      'Programmer, it is late — the moon says rest.',
      'Good morning. Sleep on that bug; it often shows itself at dawn.',
      'Good day — may today be a full moon: everything complete.',
      'Good evening. Another night with code?',
      'Lovely moonlight — look up from your screen a moment.',
      'A new week — wax like the new moon, steady growth.',
      'Late shift again? Moonlight stands with you.',
      'Good night. May your dreams be free of uncaught exceptions.',
    ],
    good: [
      'stargazing to clear the mind', 'tidying the logs', 'catching up on docs', 'an early night', 'aligning code style',
      'pruning dead code', 'backing up data', 'writing unit tests', 'a night talk with friends', 'a moonlit walk',
      'a quiet retrospective', 'drawing the star map', 'a gentle word', 'steady progress',
    ],
    bad: [
      'an all-nighter', 'busy-waiting', 'ignoring alarms', 'deploying unguarded', 'null-pointer night sailing',
      'traveling without a map', 'snapping at teammates', 'hoarding async tasks', 'running at full load', 'deleting logs', 'merging blindfolded', 'chasing every trend',
    ],
  },
}
