/**
 * 拉克丝 · 光棱圣辉（lux-radiance）语录素材。
 * 人设：德玛西亚的光之魔法少女，乐观坚定，坚信光明终将胜利。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const lux: CharacterQuoteDef = {
  skinId: 'lux-radiance',
  zh: {
    fixed: [
      '黑暗再深，也挡不住一束光。',
      '保持专注，光芒就在前方。',
      '我从不怀疑，因为希望是我最大的魔法。',
      '一起行动，我们会更强大！',
      '光明会指引我们回家。',
      '微笑吧，这可是免费的魔法。',
      '终极闪光，已经在充能了。',
      '即使最小的光，也能照亮一个人的夜。',
      '守护，是我学习的魔法的意义。',
      '别害怕黑暗，它只是光还没到的地方。',
      '光芒万丈的感觉，你也想试试吗？',
      '约束之光的每一层，都要打好基础。',
      '你说的「单元测试」，就是给魔法画好法阵吧。',
      '文档写清楚，后来的人就不会走进暗影。',
      '重构像折射，换一个角度，光还是那道光。',
      '报错是迷雾，日志是灯，一步步走。',
      '团战之前先插眼，上线之前先灰度。',
      '每个新人都是从「Hello World」这束光开始的。',
      '别把压力憋在心里，说出来，我们分担。',
      '今天的努力，会在明天发光。',
      '再复杂的系统，也是一行行代码点亮的。',
      '乐观不是天真，是明知有 bug 还敢继续写的勇气。',
      '休息也很重要，光也需要时间充能。',
      '你的坚持，比你以为的更耀眼。',
      '把复杂需求拆成小步骤，一个一个点亮。',
      '错误处理写得好，黑暗来袭也不慌。',
      '记住：你有队友，从来都不是一个人在战斗。',
      '愿光指引你的代码，也指引你的心。',
    ],
    greetings: [
      '早安，召唤师！愿今天的光特别眷顾你。',
      '你好呀，写代码的骑士，今天也要闪闪发光哦！',
      '午安！累了吗？闭上眼，晒一分钟太阳吧。',
      '晚上好，深夜的守护者，别忘了休息。',
      '辛苦了！你解决难题的样子，真的很帅气。',
      '周五快乐！愿你的周末充满阳光。',
      '新的一周，新的光芒，出发！',
      '嘿，别皱眉啦，笑一个，bug 会怕你的。',
    ],
    good: ['点亮一盏灯', '照亮一段代码', '写清注释', '鼓励一位队友', '重构法阵', '充满能量', '温柔坚定', ...GOOD_ZH_BASE],
    bad: ['独自走进黑暗', '掐灭灯火', '抱怨队友', '无防护探视野', '硬闯暗影', '耗尽蓝量', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      'However deep the dark, one beam of light gets through.',
      'Stay focused — the light is ahead.',
      'Hope is my greatest spell.',
      'Together, we are stronger!',
      'The light will guide us home.',
      'Smile! It is free magic.',
      'Final Spark, charging.',
      'Even the smallest light can lift someone\u2019s night.',
      'Protection is why I study magic.',
      'Do not fear the dark; it is just light not yet arrived.',
      'Unit testing — drawing the rune circle before the spell, yes?',
      'Write docs well, so no one walks into shadow later.',
      'Refactoring is refraction: new angle, same light.',
      'Errors are fog; logs are lamps. Walk step by step.',
      'Ward before the teamfight; canary before the launch.',
      'Every newcomer starts from the beam called "Hello World".',
      'Do not bottle up the pressure. Share it; we will carry it.',
      'Today\u2019s effort glows tomorrow.',
      'Even the grandest system is lit one line at a time.',
      'Optimism is not naivety — it is courage that codes on, bugs and all.',
      'Rest matters. Even light needs time to charge.',
      'You shine brighter than you think.',
      'Break the big feature down; light each step.',
      'Good error handling means the dark holds no fear.',
      'Remember: you have teammates. Never truly alone.',
    ],
    greetings: [
      'Good morning, summoner! May today\u2019s light favor you.',
      'Hello, knight of code — shine on today!',
      'Afternoon! Tired? Close your eyes, one minute of sun.',
      'Good evening, night guardian. Rest well.',
      'Great work! You look heroic solving that.',
      'Happy Friday! May sunshine fill your weekend.',
      'New week, new radiance. Let\u2019s go!',
    ],
    good: ['lighting a lamp', 'illuminating a module', 'clear comments', 'cheering a teammate', 'redrawing the circle', 'recharging fully', 'gentle firmness', ...GOOD_EN_BASE],
    bad: ['walking into the dark alone', 'snuffing the lamp', 'blaming teammates', 'scouting unguarded', 'charging the shadows', 'burning all your mana', ...BAD_EN_BASE],
  },
}
