/**
 * 厄运小姐 · 赏金女王（mf-bountyhunter）语录素材。
 * 人设：比尔吉沃特的赏金猎人，双枪女王，睚眦必报，气场全开。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const mf: CharacterQuoteDef = {
  skinId: 'mf-bountyhunter',
  zh: {
    fixed: [
      '赏金已悬，逃是没用的。',
      '我的枪口，从不浪费第二次瞄准。',
      '一枪一个，童叟无欺。',
      '对我开枪的人，坟头草都三尺高了。',
      '弹幕如雨，公平交易。',
      '账，总要算清的。',
      '别被我抓到把柄——我记性很好。',
      '大步流星，双枪连发。',
      '这单赏金，我接了。',
      '海上无王，我就是王。',
      '痛快，才是海盗的礼节。',
      '枪响之前，礼数周全；枪响之后，概不负责。',
      '每个 bug 都有赏金，你的名字在清单上吗？',
      '线上事故就是悬赏令，谁查出根因，赏金归谁。',
      '双枪节奏：左手复现，右手修复。',
      '别欠技术债，我可是收账的。',
      '一枪爆头是效率，弹幕覆盖是保险。',
      '海盗的规矩：先谈报酬，再谈感情。',
      '我的复仇清单很长，你的需求清单呢？',
      '瞄准要稳，出手要快，复盘要狠。',
      '金币落袋的声音，比什么都好听。',
      '海图之外是深渊，文档之外是事故。',
      '船长负责掌舵，我负责让所有人听话。',
      '交易公平：你交代码，我给喝彩。',
      '警告一次，开火一次，我很讲道理。',
      '临近周末不发版，海盗的黄金法则。',
      '火药味越浓，我越清醒。',
      '收拾干净再走——包括你的工作区。',
    ],
    greetings: [
      '早，赏金猎人。今天的猎物清单列好了吗？',
      '你好，写代码的。这单「需求」我陪你一起接。',
      '午安。擦好枪，下午有硬仗。',
      '晚上好，夜航的船长。稳住舵，别翻船。',
      '干得漂亮！这单赏金，分你一半。',
      '今日事毕！收枪，回港，喝酒。',
      '新的一周，新的悬赏榜。开工。',
      '别怂，bug 再凶，也凶不过我的双枪。',
    ],
    good: ['清点弹药', '列出悬赏', '双枪连发', '算清账目', '擦亮枪管', '收账上门', '痛快复盘', ...GOOD_ZH_BASE],
    bad: ['空枪上膛', '欠债不还', '走火伤己', '放跑目标', '账目混乱', '孤船出海', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      'The bounty is posted. Running is useless.',
      'My barrels never waste a second aim.',
      'One shot, one mark. Fair trade.',
      'Those who shot at me? Weeds waist-high on their graves.',
      'Bullet time is a fair negotiation.',
      'Accounts always settle in the end.',
      'Do not slip where I can see — my memory is excellent.',
      'Strut forward, barrels blazing.',
      'This contract, I accept.',
      'No kings at sea. Only me.',
      'Swift and clean — a pirate\u2019s courtesy.',
      'Courtesy before the shot; no refunds after.',
      'Every bug carries a bounty. Is your name on the list?',
      'An incident is a wanted poster: root cause takes the gold.',
      'Double-barrel rhythm: reproduce with the left, fix with the right.',
      'Do not owe tech debt — I collect.',
      'Headshot is efficiency; suppressing fire is insurance.',
      'Pirate rules: discuss payment before feelings.',
      'My revenge list is long. How about your backlog?',
      'Steady aim, fast draw, ruthless postmortem.',
      'Nothing sounds better than coins hitting the purse.',
      'Beyond the sea chart lies the abyss; beyond the docs, the incident.',
      'The captain steers; I keep everyone honest.',
      'A fair trade: your code, my applause.',
      'One warning, one shot. I am reasonable.',
      'No deploys on Friday — the pirate\u2019s golden rule.',
      'The stronger the gunpowder smell, the clearer my head.',
    ],
    greetings: [
      'Morning, bounty hunter. Is today\u2019s target list ready?',
      'Hello, coder. This "requirement" contract — I ride with you.',
      'Afternoon. Polish the barrels; a hard fight comes later.',
      'Evening, night captain. Hold the helm; do not capsize.',
      'Beautifully done! Half the bounty is yours.',
      'Happy Friday! Dock the ship, pour the rum.',
      'New week, new wanted board. To work.',
      'Do not flinch — no bug outguns my barrels.',
    ],
    good: ['counting the rounds', 'posting the bounty', 'double-barrel focus', 'settling accounts', 'a clean barrel', 'collecting the debt', 'a swift review', ...GOOD_EN_BASE],
    bad: ['loading blanks', 'leaving debts unpaid', 'shooting your own hull', 'letting the mark escape', 'messy ledgers', 'sailing alone', ...BAD_EN_BASE],
  },
}
