/**
 * 南宫婉 · 寒梅（nangongwan-moon）语录素材。
 *
 * 人设：掩月宗女修，端庄果决，一诺千金。语录 = 原著风台词 +
 * 程序员问候 + 「将门×工程纪律」跨界梗；黄历宜忌偏担当果决系。
 */
import type { CharacterQuoteDef } from './types.ts'

export const moon: CharacterQuoteDef = {
  skinId: 'nangongwan-moon',
  zh: {
    fixed: [
      // ── 原著风 ──
      '掩月宗一事，我自有定夺，你不必为我挂怀。',
      '韩立，若你他年证道，记得回来看我一眼。',
      '冰肌玉骨，也难抵岁月无情。',
      '这世间因果，终究自有公道。',
      '我南宫婉做事，从不后悔。',
      '朱雀赤纹燃起之日，便是血债血偿之时。',
      '寒梅傲雪，靠的不是运气，是骨气。',
      '我既应下的事，天王老子也改不了。',
      '旁人怎么看我，与我何干。',
      '宗门荣辱，一肩担之。',
      '情之一字，最是伤人，我却从未怕过。',
      '雪压枝头低，虽低不着泥。',
      '等待也是一种修行，我等得起。',
      '我的剑，只为护我想护的人出鞘。',
      '风雨越大，梅香越烈。',
      '莫劝我放下，我的执念我自己扛。',
      '出身如何不重要，重要的是走哪条路。',
      '这世道，心软的人总要吃些苦头。',
      '既然选了这条路，跪着也要走完。',
      '朱雀展翅，焚尽八荒，亦不焚我本心。',
      // ── 将门 × 工程纪律 ──
      '线上事故如风雪，扛过去，队伍就淬炼出来了。',
      '技术方案没有完美，只有取舍，决策要有担当。',
      'hotfix 如朱雀火，快、准、稳，不可恋战。',
      '代码要有风骨：简洁、直接、不绕弯。',
      '推倒重来需要勇气，守住重构更需要定力。',
      '事故复盘不是问责，是淬火。',
      'Deadline 是军令状，签了就要守。',
      '删掉的死代码，如剪去的病枝，树才长得高。',
      '性能瓶颈如敌阵核心，找准了，一击必杀。',
      '防御要做在事前，道歉要做在事后，顺序别颠倒。',
      '大版本的发布计划，要像行军布阵，粮草先行。',
      '别在情绪上头时回复邮件，如同别在怒时出剑。',
      '没有监控的系统，如同雪夜行军不设哨。',
      '接口设计要一碗水端平，前后端才能齐心。',
      '注释是承诺，写下的就要认。',
      '旧系统迁移如移营，一步一岗，不可冒进。',
      'Code review 要直言，藏着的意见是暗伤。',
      '函数过长如枝条乱生，该修就修。',
      '自动化测试是亲兵，平时多操练，战时少流血。',
      '上线 Checklist 如出征点卯，一项都不能少。',
      '值班要有交接，岗位如阵地，不可无人。',
      '依赖别人的模块，先看它的测试，再看它的文档。',
      '遇事先稳住阵脚，日志拉出来，一条条看。',
      '优雅降级，是给用户留的体面。',
      '写代码要对得起半年后接手的自己。',
      '重构不是炫技，是还债，要还就得还干净。',
      '新人心法：多问多记多复盘，三年可成主力。',
      '系统稳定如寒梅开在冬，看着安静，底下全是功夫。',
    ],
    greetings: [
      '程序员道友，早安。新的一天，当如寒梅，迎霜而上。',
      '道友日安，今日事今日毕，方是大家风范。',
      '早安，愿你今日的代码如梅枝，条理清瘦，风骨凛然。',
      '道友辛苦，难关面前，稳住阵脚，关口自破。',
      '晚上好，夜战代码，记得开一盏暖灯。',
      '午安，短憩片刻，蓄力再战。',
      '新的一周，立个目标，然后像梅一样，咬定不放松。',
      '今天好，收尾要干净，方显担当。',
      '道友，bug 如风雪，来势再猛，终会过去。',
      '早安，今日宜果断，忌犹豫。',
      '道友晚安，今天没做完的，明天堂堂正正继续。',
      '辛苦了，记住：你解决的每个难题，都是你的军功章。',
    ],
    good: [
      '直面难题', '清理死代码', '操练测试', '加固监控', '果断决策',
      '复盘淬火', '直言评审', '纪律重构', '早睡蓄力', '问候同袍',
      '修剪长函数', '巩固阵地', '演练事故', '一鼓作气',
    ],
    bad: [
      '情绪上头回复', '无哨上线', '推诿塞责', '掩盖事故', '冒进迁移',
      '恋战 hotfix', '岗位无交接', '藏着意见', '无计划冲锋', '带怒出剑', '删监控省事',
    ],
  },
  en: {
    fixed: [
      // ── novel-flavored ──
      'The sect\u2019s affairs are mine to settle; do not worry for me.',
      'Han Li, if you attain the Dao someday, come back and see me.',
      'Even ice-pure jade cannot withstand the years.',
      'Cause and effect keep their own justice, in the end.',
      'I, Nangong Wan, never regret what I have done.',
      'When the Vermilion Bird ignites, blood debts come due.',
      'Winter plum endures snow on backbone, not luck.',
      'What I have promised, not even heaven can change.',
      'Let them talk. Their eyes are their problem.',
      'Waiting is also cultivation. I can afford to wait.',
      'My blade leaves its sheath only to protect those I choose.',
      'The harder the storm, the stronger the plum fragrance.',
      'A soft heart pays a hard price in this world.',
      'The Vermilion Bird may scorch the eight wastes, never my resolve.',
      // ── command × engineering ──
      'An incident is a snowstorm — carry the team through and it comes out tempered.',
      'No perfect design, only trade-offs. Decide, and own it.',
      'A hotfix is Vermilion Bird fire: fast, precise, no lingering.',
      'Code should have backbone: lean, direct, no detours.',
      'Starting over takes courage; seeing the refactor through takes grit.',
      'A postmortem is not blame; it is quenching steel.',
      'A deadline is a battle pledge. Signed means kept.',
      'Dead code is diseased branches — prune them, and the tree grows tall.',
      'A bottleneck is the enemy\u2019s core: find it, one decisive strike.',
      'Defense before the fact, apology after — never reversed.',
      'A major release is a march: logistics first, banners second.',
      'Never answer email in anger, as never draw a blade in rage.',
      'A system without monitoring is a night march with no sentries.',
      'Design APIs even-handedly; frontend and backend fight as one.',
      'A comment is a promise. Own what you write.',
      'Migrating a legacy system is moving camp: post guards at every step.',
      'In review, speak plainly; withheld opinions are hidden wounds.',
      'An overlong function is runaway growth — prune it.',
      'Automated tests are your guard troop: drill in peace, bleed less in war.',
      'A launch checklist is roll call before battle — not one item skipped.',
      'Read a dependency\u2019s tests before its docs; trust deeds over words.',
      'When trouble strikes, hold the line: pull the logs, read them line by line.',
      'Graceful degradation is the dignity you leave your users.',
      'Ship for the engineer who inherits your code six months from now.',
    ],
    greetings: [
      'Good morning, programmer. Face the day like winter plum — into the frost.',
      'Good day. Finish today\u2019s work today; that is backbone.',
      'May your code be like plum branches: lean, ordered, unyielding.',
      'You have carried enough today. Steady — the pass will break.',
      'Good evening. Night battles deserve a warm lamp.',
      'Afternoon. Rest briefly, then strike again.',
      'A new week: set a goal and bite down like a plum in snow.',
      'Friday. A clean finish shows true character.',
    ],
    good: [
      'facing the hard problem', 'pruning dead code', 'drilling the tests', 'posting sentries', 'a decisive call',
      'a blameless postmortem', 'plain-spoken review', 'a disciplined refactor', 'an early night', 'checking on teammates',
      'trimming long functions', 'securing the position', 'running the drill', 'one strong push',
    ],
    bad: [
      'replying in anger', 'launching without sentries', 'shifting blame', 'burying an incident', 'a reckless migration',
      'lingering on hotfixes', 'skipping handover', 'hoarding opinions', 'charging without a plan', 'drawing a blade in rage', 'removing monitors to save time',
    ],
  },
}
