/**
 * 紫灵 · 紫霞（ziling-mystic）语录素材。
 *
 * 人设：妙音门主之女汪凝，狡黠灵动，快意恩仇。语录 = 原著风台词 +
 * 程序员问候 + 「妙音×产品交互」跨界梗；黄历宜忌偏巧思取趣系。
 */
import type { CharacterQuoteDef } from './types.ts'

export const mystic: CharacterQuoteDef = {
  skinId: 'ziling-mystic',
  zh: {
    fixed: [
      // ── 原著风 ──
      '一面轻纱掩倾城，世人皆道我神秘。',
      '妙音门主之女，只愿随心所欲，快意恩仇。',
      '紫霞流转处，皆是妾身的巧思。',
      '面纱之下真假难辨，你可愿听我一句真言？',
      '这星河璀璨，却不及人间知己情长。',
      '我汪凝虽出身魔道，行事却重情重义。',
      '猜人心思多累呀，不如直接问。',
      '魔道正道，不过是世人画的圈圈。',
      '妾身的曲子，只弹给懂的人听。',
      '紫雾起时，且看谁沉得住气。',
      '小女子这双眼睛，看人从没走过眼。',
      '与其猜忌，不如把酒言欢。',
      '妙音一曲，可安神，也可乱心。',
      '世人都爱看脸，妾身偏要他们看心。',
      '面纱是我的规矩，摘下便是例外。',
      '有趣的人，比有趣的法宝难得。',
      '恩要还，仇要报，中间的糊涂账慢慢算。',
      '紫霞映月，正是做事的好时辰。',
      '别看我笑，我记仇记得可清楚了。',
      '这江湖呀，认真你就输啦。',
      // ── 妙音 × 产品交互 ──
      '你们的「魔法代码」，本姑娘听着格外亲切。',
      '紫色主题最护眼，妾身早就知道了。',
      '需求评审如听曲，外行听热闹，内行听门道。',
      'UI 动效如妙音，多了乱心，少了无趣。',
      '产品经理的话，信三分，疑七分，剩下九十分看原型。',
      '神秘感是留白，注释也是留白，懂？',
      'A/B 测试，像妾身换面纱：哪面讨喜，戴哪面。',
      '改需求的人最喜新厌旧，代码可要专一。',
      '暗色模式一开，紫霞更艳了。',
      '你的终端唱的是哪一出？满屏红字，热闹得很。',
      '声音提示要有度：一声惊艳，十声聒噪。',
      '埋点如眼线，铺得巧，才知道人心所向。',
      '别把算法当玄学，玄学可没有这么准的召回率。',
      '代码整洁如梳妆，邋遢的美人也要减三分。',
      '彩蛋功能如惊喜，埋一枚就够，多了廉价。',
      '重构如换装，里子换了，气质要还在。',
      '这个 bug 挺会躲呀，可惜碰上本姑娘的神识。',
      '版本命名是门玄学，你们居然真敢用来定吉凶。',
      '用户反馈如情书，骂得越狠，爱得越深。',
      '防御性设计，跟防人是一个道理：不害人，但得防人。',
      '界面漂紫了？别慌，先截屏，再重启，最后发朋友圈。',
      '文档写得俏皮些，后人才愿意翻嘛。',
      '删功能比加功能难，这叫取舍的修行。',
      '你的报错文案冷冰冰的，换妾身来写，保证用户看了不生气。',
      '排期如赌局，押小了赶工，押大了摸鱼。',
      '祖传代码的作者早跑了，留下谜面给你们猜。',
      '新框架月月有，定力比潮流值钱。',
      '写代码如唱曲：起承转合，尾声要收得漂亮。',
    ],
    greetings: [
      '哟，程序员道友，今日的代码给你施了什么法呀？',
      '早安～妾身新泡了紫霞茶，来一杯提提神？',
      '道友好呀，听说你们那行当，头发也是修行资源？',
      '午安！偷偷说：下午三点的 bug，多是午饭没吃好。',
      '晚上好，夜里的代码自带三分魅惑，小心别被迷了去。',
      '新的一周，愿你的需求都讲道理，甲乙双方都体面。',
      '周五啦，本周的恩怨本周了，别带到周末去。',
      '道友辛苦，来，听妾身弹一曲《解压诀》。',
      '早呀，今天也要做个有趣的写代码的人。',
      '午安，茶歇一下，让灵感追上你。',
      '晚安，愿你的梦里没有改需求的人。',
      '道友，累的时候就看看紫霞，烦恼会淡一点的。',
    ],
    good: [
      '俏皮重构', '换个新思路', '润色文案', '埋点观察', '茶歇片刻',
      '问清需求', '截屏存证', '理清取舍', '调音校色', '睡个美容觉',
      '翻翻反馈', '逗趣同门', '格式化梳妆', '试一把新工具',
    ],
    bad: [
      '盲信口头需求', '乱堆动效', '彩蛋泛滥', '文案冷冰冰', '押大排期',
      '追新框架', '摸鱼成瘾', '报错吓人', '谜语人注释', '改需求成瘾', '深夜发版',
    ],
  },
  en: {
    fixed: [
      // ── novel-flavored ──
      'One veil hides a city\u2019s beauty; the world calls it mystery.',
      'Daughter of the Mystic Sound Sect, I do as I please and repay in kind.',
      'Where violet mist swirls, there goes my little scheme.',
      'Truth and lies blur beneath the veil — care for one honest line?',
      'The galaxy is bright, but a true friend outshines it.',
      'Born of the demonic path, yet I keep faith with my friends.',
      'Guessing at hearts is exhausting. Just ask.',
      'Right path, demonic path — circles drawn by lesser minds.',
      'I play my tune only for those who can hear it.',
      'When violet mist rises, watch who keeps their nerve.',
      'Fun people are rarer than fun treasures.',
      'Do not mind my smile — I remember every grudge clearly.',
      'In this jianghu, taking it too seriously is how you lose.',
      // ── mystic sound × product ──
      'Your "magic code" — a girl finds that oddly flattering.',
      'Purple themes are easiest on the eyes. I knew it first.',
      'Requirement reviews are opera: novices hear noise, masters hear intent.',
      'UI motion is music: too much muddles the mind, too little bores it.',
      'Trust a product manager three parts, doubt seven; the rest, read the prototype.',
      'Mystery is whitespace. So are comments. You follow?',
      'A/B testing is my veil-swapping: wear whichever face they like.',
      'Requirement-changers are fickle; your code should stay faithful.',
      'Dark mode on, and the violet glows deeper.',
      'What opera is your terminal singing? All red — very dramatic.',
      'Notification sounds need restraint: once delightful, ten times a nuisance.',
      'Analytics are my informants — placed well, they tell you where hearts lean.',
      'Do not call algorithms sorcery. Sorcery never had recall this good.',
      'Tidy code is like grooming: even a beauty loses three points unkempt.',
      'Easter eggs are surprises: one is charming, ten are cheap.',
      'Refactoring is a costume change: new lining, same charisma.',
      'A sneaky bug — but my spiritual sense is sneakier.',
      'Version naming as divination — and you people schedule releases by it.',
      'User feedback is a love letter: the angrier the ink, the deeper the love.',
      'Interface turned purple? Screenshot first, restart second, post about it third.',
      'Write docs with a wink — successors actually read them.',
      'Deleting a feature beats adding one; that is the discipline of trade-offs.',
      'Your error copy is freezing. Let me write it — users would smile instead of fume.',
      'Estimates are a casino: bid small and crunch, bid big and slack.',
      'The author of that legacy code is long gone — a riddle left for you.',
      'New frameworks bloom monthly; composure outvalues fashion.',
      'Code like singing a tune: rise, turn, close — finish the ending well.',
    ],
    greetings: [
      'Well well, programmer — what spell has your code cast on you today?',
      'Morning~ Fresh violet-mist tea, brewed by yours truly. Care for a cup?',
      'Hello there! I hear in your trade, hair counts as a cultivation resource.',
      'Afternoon! A secret: 3 p.m. bugs are usually lunch problems.',
      'Good evening. Night code has three parts charm — do not fall under it.',
      'A new week — may your tickets be reasonable and your clients dignified.',
      'Friday! Settle this week\u2019s grudges this week; weekends are sacred.',
      'You have worked hard. Sit — a tune of Unwinding, on me.',
    ],
    good: [
      'a playful refactor', 'a fresh angle', 'polishing the copy', 'checking the analytics', 'a tea break',
      'clarifying the ask', 'saving a screenshot', 'a clean trade-off', 'tuning the details', 'a beauty sleep',
      'reading feedback', 'teasing a teammate', 'a tidy format', 'test-driving a new tool',
    ],
    bad: [
      'trusting verbal specs', 'piling on animations', 'egg overload', 'icy error copy', 'padding every estimate',
      'chasing every framework', 'slack-line slacking', 'alarming error text', 'riddling comments', 'requirement whiplash', 'a midnight release',
    ],
  },
}
