/**
 * 萨勒芬妮 · 星颂（seraphine-anthem）语录素材。
 * 人设：用歌声施展魔法的歌姬，共情力满格，治愈系爱豆。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const seraphine: CharacterQuoteDef = {
  skinId: 'seraphine-anthem',
  zh: {
    fixed: [
      '我能听见你心里的声音，别慌，深呼吸。',
      '来吧，跟着我的节奏，一二三四！',
      '音乐会把我们连在一起，哪怕隔着整个符文之地。',
      '每一个音符，都是我想对你说的话。',
      '舞台的灯光再亮，也亮不过你们的眼睛。',
      '今天的声音，有点想念远方的海。',
      '掌声不是终点，是下一首歌的前奏。',
      '如果心情下雨，那就唱一首雨中的歌。',
      '海克斯科技的嗡鸣，也是一种旋律。',
      '嘘——听，城市在唱歌。',
      '练习一千遍，只为台上那三分钟。',
      '他们说我太吵，可世界本来就该有声响。',
      '别怕走音，真诚比完美动人。',
      '把今天的心事，写进副歌里。',
      '你说的「联调」，听起来像合唱，得对上拍子。',
      '耳机戴久了记得摘下来，听听真实的世界。',
      '这个 bug 的尖叫声，我帮你把它唱平。',
      '需求评审就是编曲，各声部都得有位置。',
      '代码也要留白，就像歌与歌之间的呼吸。',
      '上线前的安静，是副歌前的停顿，享受它。',
      '你的终端弹出来的报错，红得像舞台灯。',
      '自动部署的流水线，咔哒咔哒，多像节拍器。',
      '别一个人扛，合唱才有力量的和声。',
      '用户反馈是最诚实的听众，认真听。',
      '文档是歌词本，没有它谁都会唱错。',
      '今天也要把工作，唱成自己喜欢的样子。',
      '存档、提交、休息，三个音一个都不能少。',
      '把警报声改成铃声，心情会好一点点的。',
    ],
    greetings: [
      '亲爱的程序员，早安，今天也是适合发版的好日子！',
      '嘿，写代码的你，记得喝水哦，我盯着呢～',
      '午安！要不要来点背景音乐陪你改 bug？',
      '晚上好呀，深夜的代码需要一首安静的摇篮曲。',
      '辛苦啦，你的每一次提交，我都想鼓掌！',
      '周五快乐！这周的和弦收得很漂亮。',
      '新的一周，新的一首歌，慢慢来，别走音。',
      '道友……啊不，召唤师，今天也要开心哦！',
    ],
    good: ['彩排一遍流程', '唱着歌重构', '给同僚点赞', '写清注释', '合并一段旋律', '调亮一盏灯', '温柔沟通', ...GOOD_ZH_BASE],
    bad: ['静音消失', '抢拍上线', '对观众喝倒彩', '删掉合唱声部', '跑调硬撑', '通宵彩排', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      'I can hear the song in your heart. Breathe.',
      'Follow my rhythm — one, two, three, four!',
      'Music connects us, even across Runeterra.',
      'Every note is a word I meant to say.',
      'Stage lights are bright, but your eyes are brighter.',
      'If it rains in your heart, sing a rain song.',
      'Hextech hums a melody, if you listen.',
      'Shh — hear that? The city is singing.',
      'A thousand rehearsals for three minutes on stage.',
      'Being a little off-key is fine; sincerity carries the tune.',
      'Your "integration testing" sounds like a choir locking in.',
      'Take the headphones off sometimes; the world has a soundtrack too.',
      'That bug was screaming — I sang it flat.',
      'Requirement reviews are arranging: every voice needs a lane.',
      'Leave whitespace in code, like breaths between songs.',
      'The quiet before release is the pause before the chorus. Enjoy it.',
      'Your terminal error glows red like a stage light.',
      'A CI pipeline clicks along like a metronome.',
      'Do not carry it alone — harmonies are stronger.',
      'User feedback is the most honest audience. Listen closely.',
    ],
    greetings: [
      'Good morning, dear programmer — a fine day to ship!',
      'Hey you, writing code — drink some water, I am watching~',
      'Afternoon! Some background music for bug-fixing?',
      'Good evening. Late-night code deserves a lullaby.',
      'Great work — every commit of yours deserves applause!',
      'Happy Friday! This week resolved beautifully.',
      'New week, new song. Take it slow, stay on key.',
    ],
    good: ['a dress rehearsal', 'refactoring with a tune', 'cheering a teammate', 'clear comments', 'merging a melody', 'brightening a lamp', 'a gentle word', ...GOOD_EN_BASE],
    bad: ['going silent', 'rushing the release cue', 'booing the audience', 'deleting the harmonies', 'pushing through off-key', 'all-night rehearsals', ...BAD_EN_BASE],
  },
}
