/**
 * 娑娜 · 弦语仙音（sona-etwahl）语录素材。
 * 人设：不能言语的琴仙，以弦代言，温柔治愈，音乐即魔法。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const sona: CharacterQuoteDef = {
  skinId: 'sona-etwahl',
  zh: {
    fixed: [
      '♪ ——（一段温柔的问候旋律）',
      '♫ ——（琴弦轻拨，似在点头）',
      '♪～（这段旋律的意思是：别急，慢慢来）',
      '（她拨了一个大三和弦，空气都暖了）',
      '（竖琴悬浮着，随她的心念流转）',
      '♪（音符在说：你做得很好）',
      '（一段小调……她懂你的委屈）',
      '♫（节奏轻快起来：开工吧！）',
      '（她以弦代言，字字皆是音）',
      '♪～（这是「加油」的和弦）',
      '（急促的琶音：快看日志！）',
      '（一段渐弱音：该休息了）',
      '♪（轻柔的轮指：bug 也是乐章的一部分）',
      '（她奏出一段卡农——循环，但每次都更美）',
      '♫（低音沉稳：架构要打好地基）',
      '（泛音一串：细节决定质感）',
      '♪～（副歌之前，都需要铺垫）',
      '（她用琴声回答：重构，就是重新编曲）',
      '（一段蓝调：上线延期，也可以很美）',
      '♫（和弦解决，悬而未决的 issue 也该解决了）',
      '（她轻轻拨弦，指向你的屏幕：这个变量名，再想想）',
      '♪（八度跳跃：性能提升一倍！）',
      '（切分音响起：节奏别乱，排期要稳）',
      '（她微笑着拨出终曲的属七和弦——等你的 resolve）',
      '（一串上行音阶：升职加薪之路）',
      '♪～（今天的旋律主题：从容）',
      '（琴弓悬停：删除之前，先想三秒）',
      '（最后一个音轻轻落下：完美收官）',
    ],
    greetings: [
      '♪～（早晨的音阶：早安，写代码的人）',
      '♫（轻快的问候曲：你好呀！）',
      '♪（午后的摇篮曲：小憩片刻吧）',
      '（她奏起夜曲：晚安，别熬太晚）',
      '♫！（一串华丽的颤音：干得漂亮！）',
      '♪～（周五的圆舞曲：周末快乐）',
      '（晨曦奏鸣曲：新的一周，新的乐章）',
      '♫（她用琴声比了个心）',
    ],
    good: ['抚琴一曲', '调准音色', '写下乐谱', '温柔和声', '练习琶音', '静听反馈', '校对节拍', ...GOOD_ZH_BASE],
    bad: ['乱了节拍', '强行高音', '删掉乐谱', '无视跑调', '彻夜练琴', '孤奏无合', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      '\u266a — (a gentle greeting melody)',
      '\u266b — (a soft pluck, like a nod)',
      '\u266a~ (this phrase means: no rush, take it slow)',
      '(She plays a major third; the air turns warm.)',
      '(The etwahl floats, turning with her thoughts.)',
      '\u266a (the notes say: you did well)',
      '(A minor passage... she understands your frustration.)',
      '\u266b (the tempo lifts: time to work!)',
      '\u266a~ (the "keep going" chord)',
      '(A brisk arpeggio: check the logs!)',
      '(A decrescendo: time to rest.)',
      '\u266a (a soft roll: bugs are part of the score)',
      '(She plays a canon — loops, lovelier each time.)',
      '\u266b (steady bass: architecture needs a firm base)',
      '(A run of harmonics: details make the texture.)',
      '\u266a~ (every chorus needs its buildup)',
      '(In strings she answers: refactoring is re-arranging.)',
      '(A blues phrase: a delayed release can still be beautiful.)',
      '\u266b (the chord resolves — as should your open issue)',
      '(She plucks toward your screen: that variable name, rethink it)',
      '\u266a (an octave leap: performance doubled!)',
      '(Syncopation: keep the rhythm, keep the schedule.)',
      '(A final dominant seventh — waiting for your resolve.)',
      '(An ascending scale: the road to promotion.)',
      '\u266a~ (today\u2019s theme: composure)',
      '(The bow hovers: think three seconds before deleting.)',
      '(The last note lands softly: a perfect finish.)',
    ],
    greetings: [
      '\u266a~ (a morning scale: good day, coder)',
      '\u266b (a cheerful greeting: hello there!)',
      '\u266a (an afternoon lullaby: rest a little)',
      '(She plays a nocturne: good night, not too late)',
      '\u266b! (a brilliant trill: beautifully done!)',
      '\u266a~ (Friday\u2019s waltz: happy weekend)',
      '(A sonata for the new week: a new movement begins)',
    ],
    good: ['a song on the strings', 'tuning the tone', 'writing the score', 'a gentle harmony', 'practicing arpeggios', 'listening to feedback', 'checking the tempo', ...GOOD_EN_BASE],
    bad: ['losing the beat', 'forcing the high note', 'deleting the score', 'ignoring the off-key', 'practicing all night', 'playing alone', ...BAD_EN_BASE],
  },
}
