/**
 * 维恩 · 夜狩（vayne-nightfall）语录素材。
 * 人设：圣银弩的暗夜猎手，独行、冷静、以夜为家，猎杀黑暗中的怪物。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const vayne: CharacterQuoteDef = {
  skinId: 'vayne-nightfall',
  zh: {
    fixed: [
      '夜幕降临，猎杀开始。',
      '黑暗中的怪物，惧怕圣银的光。',
      '我不需要同伴……但你可以跟着。',
      '翻滚，闪避，然后给致命一击。',
      '银弩上膛，目标锁定。',
      '黑夜从不妨碍我，它掩护我。',
      '怪物伪装成人，bug 伪装成「小问题」。',
      '正义也许会迟到，弩箭不会。',
      '猎人最忌讳的，是弄出声响。',
      '白天属于你们，夜晚属于我。',
      '每一次暗影突袭，都要先想好退路。',
      '他们烧了我的过去，我烧掉他们的未来。',
      '盯紧目标，别被表象迷惑。',
      '三箭之内，解决战斗。',
      '孤独？那是我选择的武器。',
      '你管这叫「偶现 bug」？世上没有偶现，只有没抓到的猎物。',
      '夜里改代码，环境要静，心思要稳。',
      '复现、定位、击杀，猎人的三部曲。',
      '别惊动它——先把日志埋好，等它自己撞上来。',
      '监控就是我的夜视仪。',
      '阴影里最安全，注释里最诚实。',
      '一个真正的猎手，从不打无准备的仗。',
      '怪物会再生？那就再杀一次。',
      '冷静，是最锋利的箭头。',
      '夜巡结束，写完复盘再休息。',
      '沉默不是冷漠，是专注。',
      '白天的喧嚣与我无关，我在等夜晚的性能报告。',
      '圣银淬火，代码过测试，才算成型。',
    ],
    greetings: [
      '夜安，程序员。你的猎物出现了吗？',
      '早。我守了一夜，系统很安静，放心。',
      '午后好。眯一会儿，晚上还有硬仗。',
      '晚上好，夜晚是我们的主场。',
      '辛苦。击杀漂亮，记得写复盘。',
      '今天了。收好弩箭，享受两天的白天。',
      '新的一周，新的猎场。静候。',
      '别慌，偶现的怪物，我用日志抓过很多。',
    ],
    good: ['夜巡一遍日志', '静静守候', '锁定目标', '写好复盘', '打磨箭头', '埋好监控', '独处深思', ...GOOD_ZH_BASE],
    bad: ['打草惊蛇', '无准备上线', '惊动线上怪物', '空放弩箭', '暴露行踪', '彻夜追凶', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      'Night falls. The hunt begins.',
      'The monsters of the dark fear the silver light.',
      'I need no companion... but you may follow.',
      'Tumble, dodge, then strike true.',
      'Crossbow loaded. Target locked.',
      'The night never hinders me; it shelters me.',
      'Monsters wear human faces; bugs wear "minor issue" faces.',
      'Justice may be late. My bolts are not.',
      'A hunter\u2019s first rule: make no sound.',
      'The day is yours; the night is mine.',
      'Every ambush needs an exit planned first.',
      'They burned my past; I burn their future.',
      'Watch the target; never trust appearances.',
      'Three bolts, one fight.',
      'Solitude? It is a weapon I chose.',
      'An "intermittent bug"? Nothing is intermittent — only prey not yet caught.',
      'Fixing code at night: quiet surroundings, steady mind.',
      'Reproduce, locate, kill. The hunter\u2019s trilogy.',
      'Do not startle it — set the logs first, let it walk in.',
      'Monitoring is my night vision.',
      'Shadows are safest; comments are most honest.',
      'A true hunter never fights unprepared.',
      'The monster regenerates? Kill it again.',
      'Calm is the sharpest bolt-head.',
      'Patrol done. Write the postmortem, then rest.',
      'Silence is not coldness; it is focus.',
      'Daytime noise means nothing — I await the night\u2019s performance report.',
    ],
    greetings: [
      'Good night, programmer. Has your prey shown itself?',
      'Morning. I kept watch; the system is quiet. Relax.',
      'Afternoon. Rest your eyes — a hard fight comes tonight.',
      'Evening. The night belongs to us.',
      'Well done. Clean kill. Now write the postmortem.',
      'Friday. Store the bolts; enjoy two days of daylight.',
      'New week, new hunting ground. Waiting quietly.',
      'Do not panic. I have caught many "intermittent" monsters with logs.',
    ],
    good: ['a night patrol of logs', 'quiet patience', 'locking the target', 'a good postmortem', 'sharpening the bolt', 'setting the monitors', 'solitary focus', ...GOOD_EN_BASE],
    bad: ['startling the prey', 'launching unprepared', 'waking the prod monster', 'wasted bolts', 'exposing your position', 'hunting all night', ...BAD_EN_BASE],
  },
}
