/**
 * 亚索 · 斩风疾影（yasuo-gale）语录素材。
 * 人设：背负冤罪的浪人剑客，疾风剑道，一往无前。
 */
import type { CharacterQuoteDef } from './types.ts'
import { GOOD_ZH_BASE, BAD_ZH_BASE, GOOD_EN_BASE, BAD_EN_BASE } from './lol-shared.ts'

export const yasuo: CharacterQuoteDef = {
  skinId: 'yasuo-gale',
  zh: {
    fixed: [
      '死亡如风，常伴吾身。',
      '不可久留。',
      '且随疾风前行，身后亦须留心。',
      '此剑之势，愈斩愈烈。',
      '长路漫漫，唯剑作伴。',
      '树叶的一生，只是为了归根吗？',
      '荣耀存于心，而非流于形。',
      '吾虽浪迹天涯，却未迷失本心。',
      '一剑，一念，一次commit。',
      '风不曾停留，我也不曾。',
      '无罪之人，方可安睡。',
      '斩不断的，就再斩一次。',
      '酒逢知己，代码遇良架构。',
      '风之壁挡下弹幕，防火墙挡下流量。',
      '疾风踏斩，三段位移，正如小步快跑的发布节奏。',
      '敌人如潮水般涌来，那便如风般掠过。',
      '真正的剑客，从不抱怨剑太重。',
      '直面你的bug，像直面你的宿命。',
      '剑刃所至，需求皆平。',
      '浪客不留恋过去，正如代码不留恋旧分支。',
      '每一次挥剑，都全力以赴；每一次提交，都想清楚再动。',
      '风起之时，便是我出手之日。',
      '孤独是浪人的必修课，也是架构师的。',
      '有些事，明知不可为，仍要为之——比如祖传代码。',
      '我走得很慢，但从不后退。',
      '刀光如雪，注释如灯。',
      '面对疾风吧——bug 亦然。',
      '收剑入鞘，今日事毕。',
    ],
    greetings: [
      '早安。风起了，适合开工。',
      '写代码的旅人，前路小心，记得保存。',
      '午安。饮一杯，歇片刻，再战。',
      '夜深了。剑可入鞘，灯该熄了。',
      '辛苦。今日之战，打得漂亮。',
      '周五了。收剑，归鞘，饮酒去。',
      '新的一周，新的征途，随我来。',
      '面对疾风吧，少年——bug 也一样。',
    ],
    good: ['拔剑斩雾', '直面难题', '随风重构', '写下注脚', '小步快跑', '仗剑远行', '静心磨剑', ...GOOD_ZH_BASE],
    bad: ['背对疾风', '逃避宿命', '怨天尤人', '无鞘狂斩', '滞留原地', '轻敌冒进', ...BAD_ZH_BASE],
  },
  en: {
    fixed: [
      'Death is like the wind; always by my side.',
      'A sword is poor company to keep.',
      'Follow the wind, but watch your back.',
      'This blade never gets any lighter.',
      'The road is long; the sword, my only companion.',
      'Is a leaf\u2019s only purpose to fall?',
      'Honor is in the heart, not the name.',
      'A wanderer, yes — but never lost.',
      'One blade, one breath, one commit.',
      'The wind does not stay; neither do I.',
      'The innocent sleep easy.',
      'What cannot be cut — cut again.',
      'Good wine needs a friend; good code needs an architecture.',
      'Wind Wall blocks the barrage; a firewall blocks the traffic.',
      'Sweeping Blade three times — ship in small, quick steps.',
      'When enemies flood like the tide, move like the wind.',
      'A true swordsman never blames the weight of his blade.',
      'Face your bugs as you face your fate.',
      'Where the blade falls, requirements settle.',
      'The wanderer does not linger on old branches.',
      'Every strike, full effort; every commit, full thought.',
      'When the wind rises, I draw.',
      'Solitude is the wanderer\u2019s class — and the architect\u2019s.',
      'Some things must be done though impossible — like legacy code.',
      'I move slowly, but never backward.',
      'Blade-light like snow; comments like lamps.',
      'Face the wind — and your bugs alike.',
      'Sheathe the blade; the day\u2019s work is done.',
    ],
    greetings: [
      'Morning. The wind rises — good day to build.',
      'Traveler of code, mind the road ahead. Save your work.',
      'Afternoon. A cup of rest, then back to battle.',
      'It is late. The blade may rest; so should the lamp.',
      'Well fought today.',
      'Friday. Sheathe the sword; pour the wine.',
      'New week, new road. Follow me.',
      'Face the wind, kid — and your bugs too.',
    ],
    good: ['cutting through the fog', 'facing the hard problem', 'refactoring with the wind', 'writing the footnote', 'small quick steps', 'traveling light', 'a quiet whetstone', ...GOOD_EN_BASE],
    bad: ['turning from the wind', 'running from fate', 'blaming the world', 'slashing without a sheath', 'standing still', 'charging carelessly', ...BAD_EN_BASE],
  },
}
